_target_: dem.energies.multi_double_well_energy.MultiDoubleWellEnergy

dimensionality: 8
n_particles: 4

data_from_efm: true
data_path: "C:\\Users\\tsuna\\Documents\\Uni\\IIB\\Project\\nem_IIBProject\\configs\\data\\test_split_DW4.npy"
data_path_train: C:\\Users\\tsuna\\Documents\\Uni\\IIB\\Project\\nem_IIBProject\\configs\\data\\train_split_DW4.npy
data_path_val: C:\\Users\\tsuna\\Documents\\Uni\\IIB\\Project\\nem_IIBProject\\configs\\data\\val_split_DW4.npy

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

data_normalization_factor: 1.0

is_molecule: true

#data_path_train: "<YOURPATH>/samples_100000.pt"
#data_path_val: ${energy.data_path_train}
