_target_: dem.energies.gmm_energy.GMM

dimensionality: 2
n_mixes: 40
loc_scaling: 40
log_var_scaling: 1.0

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

should_unnormalize: true
data_normalization_factor: 50

# data_path_train: C:\Users\tsuna\Documents\Uni\IIB\Project\nem\gmm\samples_1_100000.pt
# data_path_val: ${energy.data_path_train}
