_target_: dem.energies.gmm_energy.GMM

dimensionality: 2
n_mixes: 2
loc_scaling: 2.0
log_var_scaling: -2

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

should_unnormalize: true
data_normalization_factor: 50

#data_path_train: "<YOURPATH>/samples_100000.pt"
#data_path_val: ${energy.data_path_train}
